from PIL import Image, ImageOps
import numpy as np
from PIL import ImageChops
import matplotlib.pyplot as plt
im1 = Image.open('jesien.jpg')
print("tryb", im1.mode)
print("format", im1.format)
print("rozmiar", im1.size)
T = np.array(im1)
t_r = T[:, :, 0]
im_r = Image.fromarray(t_r)
t_g = T[:, :, 1]
im_g = Image.fromarray(t_g)
t_b = T[:, :, 2]
im_b = Image.fromarray(t_b)
im2 = Image.merge('RGB', (im_r, im_g, im_b))
diff = ImageChops.difference(im1, im2)
print("Czy tablice sa rowne? ",np.array_equal(im1,im2))
r, g, b = im1.split()
print("tryb", r.mode)
print("tryb", g.mode)
print("tryb", b.mode)
diff_r = ImageChops.difference(r, im_r)
diff_g = ImageChops.difference(g, im_g)
diff_b = ImageChops.difference(b, im_b)
im3 = Image.merge('RGB', (g, r, b))
#im3.show()
#im2.show()
diff_im = ImageChops.difference(im1,im2)
#diff_im.show()
im3.save("im3.jpg")
im3.save("im3.png")
im3_png = Image.open("im3.png")
im3_jpg = Image.open("im3.jpg")
diff_im3 = ImageChops.difference(im3_png,im3_jpg)
diff_im3.show()
print("Czy tablice sa rowne? ",np.array_equal(im3_png,im3_jpg))

ob1_jpg = Image.open("obraz1_2.jpg")
ob1_png =Image.open("obraz1_2.png")
ob2_jpg =Image.open("obraz1_1N.jpg")
ob2_png =Image.open("obraz1_1N.png")
ob3_jpg =Image.open("obraz1_2N.jpg")
ob3_png =Image.open("obraz1_2N.png")
diff_ob1 = ImageChops.difference(ob1_jpg,ob1_png)
diff_ob2 = ImageChops.difference(ob2_jpg,ob2_png)
diff_ob3 = ImageChops.difference(ob3_jpg,ob3_png)
plt.figure(figsize=(32, 16))
plt.subplot(3,3,1)
plt.imshow(ob1_jpg, "gray")
plt.axis('off')
plt.subplot(3,3,2)
plt.imshow(ob1_png, "gray")
plt.axis('off')
plt.subplot(3,3,3)
plt.imshow(diff_ob1, "gray")
plt.axis('off')
plt.subplot(3,3,4)
plt.imshow(ob2_jpg, "gray")
plt.axis('off')
plt.subplot(3,3,5)
plt.imshow(ob2_png, "gray")
plt.axis('off')
plt.subplot(3,3,6)
plt.imshow(diff_ob2, "gray")
plt.axis('off')
plt.subplot(3,3,7)
plt.imshow(ob3_jpg, "gray")
plt.axis('off')
plt.subplot(3,3,8)
plt.imshow(ob3_png, "gray")
plt.axis('off')
plt.subplot(3,3,9)
plt.imshow(diff_ob3, "gray")
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.show()
